python_test/equation_roots/urls.py
from django.urls import include, path
from .views import *

urlpatterns = [
    path('', EquationRootsCreateView.as_view(), name='roots'),
    path('solution/<int:pk>', EquationRootsDetailView.as_view(), name='solution'),
    #path('', index, name='home'),
]

python_test/python_test/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('roots/', include('equation_roots.urls')),
    path('randoms/', include('randoms.urls')),
]

python_test/randoms/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', BallNumberCreateView.as_view(), name='entry'),
    path('guess/<int:pk>', BallNumberDetailView.as_view(), name='guess'),
]

python_test/equation_roots/models.py
from django.db import models
from django.urls import reverse

class EquationValues(models.Model):
    a = models.IntegerField()
    b = models.IntegerField()
    c = models.IntegerField()

    def get_absolute_url(self):
        return reverse('solution', kwargs={'pk': self.pk})

python_test/randoms/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Ball(models.Model):
    ball = models.IntegerField()

    def get_absolute_url(self):
        return reverse('guess', kwargs={'pk': self.pk})

python_test/equation_roots/forms.py
from django import forms
from .models import EquationValues

class AddEquationValues(forms.ModelForm):
    class Meta:
        model = EquationValues
        fields = ['a', 'b', 'c']

python_test/randoms/forms.py
from django import forms
from .models import Ball

class AddBallNumber(forms.ModelForm):
    class Meta:
        model = Ball
        fields = ['ball',]

python_test/equation_roots/views.py
import math
from django.shortcuts import render
from django.views.generic import CreateView, DetailView
from .models import EquationValues
from .forms import AddEquationValues

"""
Функция нахождения корней
"""
def roots(a, b, c):
    D = b**2 - 4 * a * c
    print("D = ", D)

    if D > 0:
        x1 = (-b + math.sqrt(D)) / (2 * a)
        x2 = (-b - math.sqrt(D)) / (2 * a)
        return("x1 = %.2f \nx2 = %.2f" % (x1, x2))
    elif D == 0:
        x = -b / (2 * a)
        return("x = %.2f" % x)
    else:
        return("Нет решений уравнения")

"""
Класс представления ввода пользовательских данных
"""
class EquationRootsCreateView(CreateView):
    form_class = AddEquationValues
    template_name = 'equation_roots/roots.html'

"""
Класс представления вывода решения уравнения
"""
class EquationRootsDetailView(DetailView):
    model = EquationValues
    template_name = 'equation_roots/solution.html'
    context_object_name = 'solution'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        values = self.get_object()
        context['D'] = int( values.b**2 - 4 * values.a * values.c )
        context['roots'] = roots(values.a, values.b, values.c)
        context['no_solution'] = 'Нет решений уравнения'
        context['single_solution'] = 'Одно решение уравнения'
        context['two_solutions'] = 'Два решения уравнения'
        return context

python_test/python_test/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

python_test/randoms/views.py
from random import randint
from django.views.generic import CreateView, DetailView
from .models import Ball
from .forms import AddBallNumber

"""
Функция рандомайзера
"""
def randoms(ball):
    random = []
    blue = 0
    green = 0
    red = 0
    for i in range(0, 100):
        while blue < 50 or green < 30 or red <20:
            random.append(randint(1,3))
            if random[i] == 1:
                blue += 1
                if blue >= 50:
                    break            
            elif random[i] == 2:
                green += 1
                if green >= 30:
                    break
            elif random[i] == 3:
                red += 1
                if red >= 20:
                    break
    return(random[ball])

"""
Класс представления ввода пользовательских данных
"""
class BallNumberCreateView(CreateView):
    form_class = AddBallNumber
    template_name = 'randoms/entry.html'
# Create your views here.

"""
Класс представления вывода цвета предмета
"""
class BallNumberDetailView(DetailView):
    model = Ball
    template_name = 'randoms/output.html'
    context_object_name = 'guess'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        ball = self.get_object()
        context['number'] = ball.ball
        context['randoms'] = randoms(ball.ball)
        context['blue'] = 'Синий цвет'
        context['green'] = 'Зеленый цвет'
        context['red'] = 'Красный цвет'
        return context

python_test/templates/equation_roots/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Equation roots</title>
</head>
<body>
    {% block content %}
    <form action="{% url 'roots' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            {{ form.non_field_errors }}
            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.a.errors }}
                <label for="id_a">Введите а:</label>
                {{ form.a }} </br> 
              </div>
              <div class="fieldWrapper">
                {{ form.b.errors }}
                <label for="id_b">Введите b:</label>
                {{ form.b }} </br>
              </div>
              <div class="fieldWrapper">
                {{ form.c.errors }}
                <label for="id_c">Введите c:</label>
                {{ form.c }} </br>
              </div>
            </div>
        </div>
        <div>
            <button type="submit">Добавить</button>
        </div>
    </form>
    {% endblock %}
</body>
</html>

python_test/templates/equation_roots/roots.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Корни уравнения</title>
</head>
<body>
    {% block content %}
    <h2>Проверка корней уровнения</h2>
    <form action="{% url 'roots' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            {{ form.non_field_errors }}
            <div class="col-md-4">
              <div class="fieldWrapper">
                {{ form.a.errors }}
                <label for="id_a">Введите а: </label>
                {{ form.a }}
              </div>
              <br/>
              <div class="fieldWrapper">
                {{ form.b.errors }}
                <label for="id_b">Введите b:</label>
                {{ form.b }}
              </div>
              <br/>
              <div class="fieldWrapper">
                {{ form.c.errors }}
                <label for="id_c">Введите c:</label>
                {{ form.c }}
              </div>
              <br/>
            </div>
        </div>
        <div>
          <p>Для уровнения: a * x^2 + b * x + c = 0</p>
        </div>
        <div>
            <button type="submit">Добавить</button>
        </div>
    </form>
    {% endblock %}
</body>
</html>

python_test/templates/equation_roots/solution.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Решение квардратного уровнения</title>
</head>
<body>
    {% block content %}
    <h1>Решение</h1>
    {% if D == 0 %}
        {{single_solution}}
    {% elif D > 0 %}
        {{two_solutions}}
    {% endif %}
    <br/>{{roots}}<br/>
    <a href="{% url 'home' %}">
        <button>ОК</button>
    </a>    
    {% endblock %}
</body>
</html>

python_test/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Тестовые задания</title>
</head>
<body>
{% block content %}
<h1>Тестовые задания Python-программисту</h1>
<a href="{% url 'roots' %}">
<button>Корни уровнения</button>
</a>
<pre>
<a href="{% url 'entry' %}">
<button>Генератор случайных чисел</button>
</a>
</pre>
{% endblock %}
</body>
</html>

python_test/templates/randoms/entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Угадайка</title>
</head>
<body>
{% block content %}
<h1>Угадай какого цвета лежит предмет в мешке</h1>
<form action="{% url 'entry' %}" method="POST">
    {% csrf_token %}
    <div class="row">
        {{ form.non_field_errors }}
        <div class="col-md-4">
          <div class="fieldWrapper">
            {{ form.ball.errors }}
            <label for="id_ball">Введите число от 1 до 100: </label>
            {{ form.ball }}
          </div>
          <div>
            <button type="submit">Добавить</button>
        </div>
    </div>
</form>
{% endblock %}
</body>
</html>

python_test/templates/randoms/output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% block content %}
<h1>Цвет шара</h1>
{% if randoms == 1 %}
    {{blue}}
{% elif randoms == 2 %}
    {{green}}
{% elif randoms == 3 %}
    {{red}}
{% endif %}
<a href="{% url 'home' %}">
    <button>ОК</button>
</a>    
{% endblock %}
</body>
</html>